CREATE DATABASE tp_2;
USE tp_2;

CREATE TABLE clients(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
companyName VARCHAR (30) NOT NULL, 
firstName VARCHAR (30) NOT NULL, 
lastName VARCHAR (30) NOT NULL,
email VARCHAR (70) NOT NULL,
phone VARCHAR (30) NOT NULL,
address VARCHAR (150) NOT NULL,
zipCode VARCHAR (10) NOT NULL,
city VARCHAR (30) NOT NULL,
country VARCHAR (30) NOT NULL,
state INTEGER (1) NOT NULL
);

CREATE TABLE orders(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
typePresta VARCHAR (30) NOT NULL, 
designation VARCHAR (30) NOT NULL, 
clientId INTEGER NOT NULL, FOREIGN KEY (clientId) REFERENCES clients(id) ON DELETE RESTRICT,
nbDays INTEGER NOT NULL,
unitPrice FLOAT(4,2)
state INTEGER (1) NOT NULL
);

